### ISSUE TITLE
use pip-tools

### ISSUE THREAD

**Issue by bbelderbos** [CodeConnoisseur74/pdi-to-do-list#1]
Using pip-tools to manage Python dependencies
https://www.youtube.com/watch?v=G8PApVvdkjQ

**Comment by CodeConnoisseur74** [comment]
![pip-tools](https://github.com/CodeConnoisseur74/pdi-to-do-list/assets/106032462/7ae5df98-e05d-4382-a44e-8945543da371)

**Comment by bbelderbos** [comment]
Excellent 🎉
